fix

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -18,21 +18,21 @@ jobs:
           POSTGRES_PASSWORD: stackquiz@123
           POSTGRES_DB: stackquiz-db
         ports: ["5432:5432"]
-        options: >-
-          --health-cmd="pg_isready -U stackquiz-user"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5
+        # options: >-
+        #   --health-cmd="pg_isready -U stackquiz-user"
+        #   --health-interval=10s
+        #   --health-timeout=5s
+        #   --health-retries=5
 
       # Temporary Redis for CI testing
       redis:
         image: redis:7
         ports: ["6379:6379"]
-        options: >-
-          --health-cmd "redis-cli ping || exit 1"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5
+        # options: >-
+        #   --health-cmd "redis-cli ping || exit 1"
+        #   --health-interval=10s
+        #   --health-timeout=5s
+        #   --health-retries=5
 
     steps:
       # Checkout code
@@ -67,18 +67,8 @@ jobs:
       # Push Docker Image to DockerHub
       - name: Push Docker image
         run: |
-          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-          docker tag stackquiz-backend:latest ${{ secrets.DOCKER_USERNAME }}/stackquiz-backend:latest
-          docker push ${{ secrets.DOCKER_USERNAME }}/stackquiz-backend:latest
+         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+         docker tag stackquiz-backend:latest ${{ secrets.DOCKER_USERNAME }}/stackquiz-backend:latest
+         docker push ${{ secrets.DOCKER_USERNAME }}/stackquiz-backend:latest
 
-    #   # Deploy Backend to VM
-    #   - name: Deploy Backend on VM
-    #     uses: appleboy/ssh-action@v1.0.0
-    #     with:
-    #       host: ${{ secrets.VM_HOST }}
-    #       username: ${{ secrets.VM_USER }}
-    #       key: ${{ secrets.SSH_KEY }}
-    #       script: |
-    #         cd /home/${{ secrets.VM_USER }}/app
-    #         docker pull ${{ secrets.DOCKER_USERNAME }}/stackquiz-backend:latest
-    #         docker compose up -d backend
+
